env: 
proto: 
domain_name: 
ssh_public_key_deployer:  
bootstrap_user: 
bootstrap_key_path: 

secor_azure_container_name: ""
secor_alerts_slack_channel: ""

sunbird_private_storage_account_name: # Azure account name for analytics api contents
sunbird_artifact_storage_account_name: # Azure stroage account name used for artifact upload
sunbird_public_storage_account_name:

default_org_hash_id: "" # channel id of the organization

# Data products monitoring web hooks
data_exhaust_webhook_url: ""   ## Slack webhook url
data_exhaust_Channel: ""      # Slack channel for data products alerts
data_exhaust_name: "datapipeline-monitoring"  # you can leave this as default and is not required to change

# Media content
stream_base_url: "" # Media service streaming url
media_service_azure_tenant: "" # value have to be defined
media_service_azure_tenant: ""
media_service_azure_subscription_id: ""
media_service_azure_account_name: ""
media_service_azure_resource_group_name: ""
media_service_azure_token_client_key: ""
media_service_azure_token_client_secret: ""

# kafka topic required by core #
# Please do not change this #
ingestion_kafka_topics:
  - name: telemetry.ingestion
    num_of_partitions: 4
    replication_factor: 1
    retention_time: 604800000
  - name: telemetry.ingest
    num_of_partitions: 4
    replication_factor: 1
# Geo location related var
maxmind_db_license_key:

postgres:
  db_url: "{{ groups['postgres'][0] }}"
  db_username: analytics
  db_name: analytics
  db_password: "{{dp_vault_pgdb_password}}"
  db_table_name: "{{env}}_consumer_channel_mapping"
  db_port: 5432
  db_admin_user: postgres
  db_admin_password: "{{dp_vault_pgdb_admin_password}}"

druid_postgres_user: druid # Don't change this
sunbird_private_azure_report_container_name: 'reports'
sunbird_public_azure_report_container_name: 'public-reports'
sunbird_druid_storage_account_name: 

# docker hub details
dockerhub: 
imagepullsecrets: "{{env}}registrysecret"

kubeconfig_path: /var/lib/jenkins/secrets/k8s.yaml
private_ingressgateway_ip: 

