apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: tekton-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: index.docker.io/keshavprasad/echo
        resources:
          limits:
            memory: "100Mi"
            cpu: "50m"
        ports:
        - containerPort: 9595