---
- hosts: local
  gather_facts: no
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  pre_tasks:
    - name: check for kong db migration
      include_role: 
        name: kong-migration
  roles:
    - "{{ role_name }}"

