############## Admin ######################
############## LP ######################
lp_vault_youtube_api_key: 
lp_vault_dial_service_authorization: 

# Storage Account credentials for Knowledge Platform
sunbird_private_storage_account_key:
sunbird_public_storage_account_key:
sunbird_management_storage_account_key:
sunbird_artifact_storage_account_key:
sunbird_artifact_storage_account_sas:

core_vault_docker_registry_url: 
core_vault_docker_registry_user: 
core_vault_docker_registry_password:

# You can leave these as defaults
lp_vault_graph_passport_key: "long-secret-to-calm-entropy-gods" # can be any random string, it's not necessary need to change this
