- hosts: mongo
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  vars:
    mongodb_replication_params:
    mongodb_conf_auth: true
    mongodb_conf_replSet: mongors
    mongodb_conf_dbpath: /var/lib/mongodb
    mongodb_conf_bind_ip: 0.0.0.0
    mongodb_conf_port: 27017
    mongodb_login_host: "{{ groups['mongo_master'][0] }}"
    host_name: "{{ groups['mongo_master'][0] }}"
  roles:
    - mongodb-cluster
