---
# tasks file for sunbird-monitoring
- name: tempating variables
  template:
    src: "{{ item }}.yaml"
    dest: "/tmp/{{item}}.yaml"
  with_items: "{{ monitoring_stack }}"

- name: Creating sunbird monitoring stack
  shell: "helm upgrade --install --cleanup-on-fail {{ item }} {{chart_path}}/{{ item }} --namespace monitoring -f /tmp/{{ item }}.yaml --force"
  with_items: "{{ monitoring_stack }}"

- name: Creating sunbird monitoring grafana dashboards
  shell: "helm upgrade --install --cleanup-on-fail grafana-dashboards {{chart_path}}/dashboards --namespace monitoring --force"
  tags:
    - dashboards

- name: Install statsd-exporter
  shell: "helm upgrade --install --cleanup-on-fail statsd-exporter {{chart_path}}/statsd-exporter --namespace {{ namespace }} --force"
  tags:
    - statsd-exporter
